name: Qodana
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}  # to check out the actual pull request commit, not the merge commit
          fetch-depth: 0  # a full history is required for pull request analysis

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: true
          args: --source-directory,qodana-sub,--linter,qodana-jvm-community

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: qodana-report
          path: ${{ runner.temp }}/qodana/results/report
